# Generated by Django 3.0.3 on 2020-02-10 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('image', models.ImageField(default='abc.jpg', upload_to='images/')),
                ('body', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('icon', models.ImageField(default='abc.jpg', upload_to='images/')),
                ('vote_total', models.IntegerField(default=1)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
